<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>JadeDbClient</PackageId>
    <Version>1.6.17</Version> 
    <Authors>KausCoder</Authors>
    <Description>Simplified ADO.NET-style access for SQL Server, MySQL, PostgreSQL. Unified API, parameterized queries, fluent builder, dialect-aware paging and identity handling, multiple connection support.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/KaustavCodes/JadeDbClient-DotNet</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="JadeDbClient.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="" Link="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Attributes/" />
    <Folder Include="Enums/" />
    <Folder Include="Helpers/" />
  </ItemGroup>

  <ItemGroup>
    <!-- Reference the generator to include it in the build -->
    <ProjectReference Include="../JadeDbClient.SourceGenerator/JadeDbClient.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    
    <!-- Pack the generator DLL into the 'analyzers/dotnet/cs' folder of the NuGet package -->
    <None Include="..\JadeDbClient.SourceGenerator\bin\Release\netstandard2.0\JadeDbClient.SourceGenerator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>
</Project>

